// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package provider

import (
	"sync"
	"tinder/config"
	"tinder/domain"
	"tinder/internal/user/repo"
	"tinder/internal/user/service"
)

// Injectors from wire.go:

func NewService() (domain.Service, error) {
	repository := NewRepo()
	domainService := service.NewService(repository)
	return domainService, nil
}

// wire.go:

var cg *config.Config

var configOnce sync.Once

func NewConfig() *config.Config {
	configOnce.Do(func() {
		cg = config.NewConfig()
	})
	return cg
}

var repoTemp domain.Repository

var repoOnce sync.Once

func NewRepo() domain.Repository {
	repoOnce.Do(func() {
		repoTemp = repo.NewUserRepository()
	})
	return repoTemp
}
